# Site settings
title: mediachicken
subtitle:
baseurl:
url: "https://mediachicken.com"
copyright: "&copy; 2008-2016"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: "UA-45958072-2"
disqus_shortname:
github:
  username: mediachicken
